<?php
require_once dirname(__FILE__) . '/../Cookie.php';
/**
 * Test class for Auth_Storage_Cookie.
 * Generated by PHPUnit on 2013-01-17 at 13:33:20.
 */
class Auth_Storage_CookieTest extends PHPUnit_Framework_TestCase
{
    protected $_object;
    protected function setUp()
    {
        $privateKey = 'T2%y,ttNyo.Su0{xT2%y,ttNyo.Su0{x';
        $_COOKIE = array(
            'k' => 'DLpKJGEMwQY0YBpfq387t3GyjhiswfsHBfPpjqMSQjQ=',
            'v' => 'eJxjMtsf8FR0vXaToe6G3DrhPdsTzCP4dp5ouy0SF9VfIG4JANclDRc=',
        );
        $this->_object = new Auth_Storage_Cookie($privateKey, 'k', 'v', MCRYPT_RIJNDAEL_256);
    }
    protected function tearDown()
    {
    }
    public function testIsEmpty()
    {
        $this->assertFalse($this->_object->isEmpty());
    }
    public function testRead()
    {
        $this->assertEquals(65535, $this->_object->read());
    }
    public function testWrite()
    {
        $fixture = array(
            'bool' => true, 
            'string' => 'тЕкст1',
            'float' => -999.999
        );
        $this->_object->write($fixture);
        $this->assertEquals($fixture, $this->_object->read());
    }
    public function testClear()
    {
        $this->_object->clear();
        $this->assertTrue($this->_object->isEmpty());
    }
}

